### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by mikeydiamonds** [hundio/status.js#9]
I realize this widget is no longer maintained but was curious if there's a way to change the css? I want the status text to be white. I have tried to set .status-widget__state and .block-system-status in CSS with no success. Thanks for any help.

**Comment by laCour** [comment]
Hi there,

This widget is actively maintained. If you encounter a bug or have a feature request, you're encouraged to file an issue.

Here's an example of what you're wanting to accomplish: https://jsbin.com/wagiduzecu/edit?html,css,output

You'll need to set these properties as `!important` if you're just overriding its styles like this. Otherwise, the widget offers a `css` option to disable inclusion of the provided CSS so that you can use your own styles entirely if you choose to do so.

**Comment by mikeydiamonds** [comment]
Thanks @laCour, that work perfectly.
